services:
  - type: web
    name: donate-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /ready
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_JWT_ACCESS_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://donate-app-5vhs.onrender.com
      - key: PUBLIC_APP_URL
        value: https://donate-app-5vhs.onrender.com
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        generateValue: true
